/** @type {import('next').NextConfig} */
const nextConfig = {
  env: {
    PAYMENT_CONTRACT_ADDRESS: process.env.PAYMENT_CONTRACT_ADDRESS,
    USDC_ETH_MAINNET_ADDRESS: process.env.USDC_ETH_MAINNET_ADDRESS,
    TEST_USER_ADDRESS: process.env.TEST_USER_ADDRESS,
    TEST_COURSE_ID: process.env.TEST_COURSE_ID,
    LOCAL_RPC_ENDPOINT: process.env.LOCAL_RPC_ENDPOINT,
    TEST_USER_PRIVATE_KEY: process.env.TEST_USER_PRIVATE_KEY,
    SOURCE_MINTER_ADDRESS: process.env.SOURCE_MINTER_ADDRESS,
    CERTIFICATE_SEPOLIA_ADDRESS: process.env.CERTIFICATE_SEPOLIA_ADDRESS,
    SEPOLIA_RPC_URL: process.env.SEPOLIA_RPC_URL,
    SEPOLIA_CHAIN_ID: process.env.SEPOLIA_CHAIN_ID,
    ARBITRUM_CHAIN_ID: process.env.ARBITRUM_CHAIN_ID,
    SEPOLIA_PRIVATE_KEY: process.env.SEPOLIA_PRIVATE_KEY,
    ARBITRUM_DESTINATION_CHAIN_CONTRACT: process.env.ARBITRUM_DESTINATION_CHAIN_CONTRACT,
    ARBITRUM_DESTINATION_CHAIN_SELECTOR: process.env.ARBITRUM_DESTINATION_CHAIN_SELECTOR
  },
};

export default nextConfig;
