const courses = [
    {
      id: 1,
      title: "Become a Certified Web Developer: HTML, CSS and JavaScript",
      type: "development",
      duration: "16",
      author: "Wisdom Umanah",
      fees: "50",
      cashback: "20",
      rating: 4,
      thumbnail: "./course_thumbnails/course1.jpg",
      tags: ["new"],
    },
  
    {
      id: 2,
      title: "Javascript for Beginners",
      type: "development",
      duration: "16",
      author: "Mayank",
      fees: "30",
      cashback: "10",
      rating: 5,
      thumbnail: "./course_thumbnails/course2.jpg",
      tags: ["popular", "new"],
    },
    {
      id: 3,
      title: "Become a Certified Web Developer: HTML, CSS and JavaScript",
      type: "development",
      duration: "16",
      author: "Sudhanshu Kumar",
      fees: "50",
      cashback: "20",
      rating: 5,
      thumbnail: "./course_thumbnails/course3.jpg",
      tags: ["popular", "new"],
    },
    {
      id: 4,
      title: "Become a Certified Web Developer: HTML, CSS and JavaScript",
      type: "development",
      duration: "16",
      author: "Chinmoy and Alex",
      fees: "50",
      cashback: "20",
      rating: 3,
      thumbnail: "./course_thumbnails/course4.jpg",
      tags: [],
    },
  
    {
      id: 5,
      title: "Become a Certified Web Developer: HTML, CSS and JavaScript",
      type: "development",
      duration: "16",
      author: "Chinmoy and Alex",
      fees: "50",
      cashback: "20",
      rating: 3,
      thumbnail: "./course_thumbnails/course4.jpg",
      tags: [],
    },
    {
      id: 6,
      title: "Become a Certified Web Developer: HTML, CSS and JavaScript",
      type: "development",
      duration: "16",
      author: "Chinmoy and Alex",
      fees: "50",
      cashback: "20",
      rating: 3,
      thumbnail: "./course_thumbnails/course4.jpg",
      tags: [],
    },
    {
      id: 7,
      title: "Become a Certified Web Developer: HTML, CSS and JavaScript",
      type: "development",
      duration: "16",
      author: "Chinmoy and Alex",
      fees: "50",
      cashback: "20",
      rating: 3,
      thumbnail: "./course_thumbnails/course4.jpg",
      tags: [],
    },
  ];

  module.exports = {
    courses
  }